# SPDX-License-Identifier: GPL-2.0-only

# CIX uses custom scmi_perf_domain in drivers/soc/arm/ instead
obj-$(CONFIG_ARM_SCMI_POWER_DOMAIN) += scmi_pm_domain.o
obj-$(CONFIG_ARM_SCPI_POWER_DOMAIN) += scpi_pm_domain.o
